### ISSUE TITLE
Product Description Page

### ISSUE THREAD

**Issue by pkadam96** [pkadam96/rednerds#1]
## Objective
Provide an overview of the product.

## Tasks

- [x] Create `ProductDescription` functional component.
- [x] Add textual description and Image of office chair
- [x] Add a "START" Button
- [x] Implement navigation logic to move to Parts Selection Page on button click.
