### ISSUE TITLE
Parts Selection Page

### ISSUE THREAD

**Issue by pkadam96** [pkadam96/rednerds#2]
## Objective
Allow users to select parts for assembling the product.

## Tasks

- [x] Create `PartsSelection` functional component
- [x] Create a JavaScript object to store parts data (image and name)
- [x] Create cards with images and names.
- [x]  Implement selection mechanism with checkboxes and manage state
