### ISSUE TITLE
Assembly Page

### ISSUE THREAD

**Issue by pkadam96** [pkadam96/rednerds#3]
## Objective
Enable users to drag and drop selected parts to assemble the product.

## Tasks

- [x] Create a functional component Assembly.
- [x] Use React DnD to manage drag-and-drop functionality
- [x] Display selected parts in a vertical panel
- [x] Allow users to drag parts to an assembly area
